SECTOR_SYMBOL_MAP = {
    # Individual stocks
    "2330": "semiconductor",
    "2454": "semiconductor",
    "2303": "semiconductor",
    "NVDA": "semiconductor",
    "AMD": "semiconductor",
    "INTC": "semiconductor",
    "AAPL": "technology",
    "MSFT": "technology",
    "GOOGL": "technology",
    "AMZN": "consumer",
    "META": "communication",
    "JPM": "financial",
    "BAC": "financial",
    "WFC": "financial",
    "GS": "financial",
    "C": "financial",
    "XOM": "energy",
    "CVX": "energy",

    # ETFs
    "0050": "broad_market",
    "0056": "high_dividend",
    "00878": "high_dividend",
    "00887": "broad_market",
    "QQQ": "thematic",
    "SPY": "broad_market",
    "VOO": "broad_market",
    "VTI": "broad_market",
    "IWM": "broad_market",
    "VEA": "broad_market",
    "VWO": "broad_market",
}
